### ISSUE TITLE
Avoid including article stubs in infinite

### ISSUE THREAD

**Issue by schneidan** [freejoe76/infinite-article#15]
Discovered a bunch of article stubs from Reverb, Shiny Objects, etc., in an infinite scroll today. the formatting, especially for Reverb, is a wreck. 

![infinite-reverb-stub](https://cloud.githubusercontent.com/assets/1051561/5591281/5e2fb554-910f-11e4-83f5-a9e51098df5a.png)

In addition, the links and URLs for the stubs never trigger the redirect to Wordpress for these articles, and we risk creating duplicate comment threads, among other things.

Stubs pull in photo captions without their photos in the text of articles, and lose much formatting that, at best, makes them hard/confusing to read, and at worst, could place things together far enough out of context as to appear libelous or at least correction-worthy.

"Share this article" links lead to the NGPS stub and encourage readers to share links to these monstrous pseduo-posts.

No images are displayed (Stubs have an image set to display, but with no article position assigned).

Stubs never update if a correction is made to the WP post.

I'm not sure what the solution here is, though I can think of a few possibilities: Change the feeds that power infinite, change the way NGPS assembles the feeds (exclude stubs), change the way stubs behave (if URL is hit, 301 redirect triggers, rather than origin URL only being used to create links in Complex Listing portlets), change production (don't put stubs in Display Groups that power infinite, maybe?).

**Comment by freejoe76** [comment]
Hi Dan, thanks for the screenshot.

A few notes and questions:

1. Can you add a URL for a stub to this issue?

2. I went through the infinite articles on an entertainment article today (started here: http://www.denverpost.com/music/ci_27241895/here-are-5-highlights-brighten-winter-concert-season ), and everything looked fine. I asked the online team how often stubs are used on the site, they said ten times a day.

3. You're right, there isn't a programmatic way to identify stubs. That makes this issue complicated.

**Comment by freejoe76** [comment]
Filed a ticket with MNGi asking them to append the word "stub-" to the beginning of the URL Text field value on each blog post stub.

**Comment by freejoe76** [comment]
MNGI declined to make the changes we needed to accomplish this.
