### ISSUE TITLE
Avoid including empty articles

### ISSUE THREAD

**Issue by schneidan** [freejoe76/infinite-article#17]
This article:

http://www.denverpost.com/sports/ci_27308930/live-john-elway-addresses-media-after-john-fox

appears currently in infinite scrolling. It appears to be using a JS redirect freeform, but the result in infinite scroll is an empty article with just a headline and photo:

![no-article-body](https://cloud.githubusercontent.com/assets/1051561/5730919/a995831c-9b3b-11e4-9fb0-e6fdabba9a63.png)

Possible solution: test article body content for a minimum number of paragraph elements before continuing?

**Comment by freejoe76** [comment]
Let's see how often this is an issue. For the next seven days, every time you see an article that's empty like this, update this thread with the URL of that article. I'll do the same.

**Comment by freejoe76** [comment]
I updated the back-end script to strip out redirects, but I should probably update it to eliminate those articles from the list.

**Comment by freejoe76** [comment]
This is good enough for now.
