### ISSUE TITLE
Marni Jameson-section articles disappear in the middle of the page load.

### ISSUE THREAD

**Issue by ericjlubbers** [freejoe76/infinite-article#21]
All of Marni Jameson's columns are pulling a disappearing act and causing a cascade of headlines: http://www.denverpost.com/marnijameson

**Comment by freejoe76** [comment]
I looked into this and this happens whether the infinite-article javascript loads or not. I investigated further and the Marni Jameson article layout was missing some portlets that were common on other columnist sections, so I went in and added those portlets (all region 3 portlerts). Adding those missing portlets did not fix the issue. cc @rebeccarisch

**Comment by freejoe76** [comment]
Filed a ticket with DFM.

**Comment by freejoe76** [comment]
This is fixed.
