### ISSUE TITLE
NDN Perfect Pixel issue.

### ISSUE THREAD

**Issue by schneidan** [freejoe76/infinite-article#4]
NDN video's "Perfect Pixel" tags are written onto the page in freeforms immediately above and immediately below the article portlets, and thus not included in the article skeleton for infinite scroll.

My proposed solution is this:

Replace the current three-freeform method with something more like:

function putOnPerfectPixel() {
  if ($('#articleHeader).html().length ==0) {
    $('articleHeader.html('#perfectpixel upper div here');
  }
  if ($('#articleFooter).html().length ==0) {
    $('articleFooter.html('#perfectpixel lower div here');
  }
  <Script src="#ndn perfect pixel script"></script>
}
putOnPerfectPixel();

Could be written to run on a regular article, or target a certain instance (the current instance) of infinite scroll after the article is written ... written correctly, I could put this in the commenting freeform and it would them be avaialble on the page for the rest of the articles, so you'd just have to add the function call?

**Comment by schneidan** [comment]
Asking again as I can't even find the email thread I thought I asked on...

**Comment by freejoe76** [comment]
Any update?

**Comment by schneidan** [comment]
Tyler kicked it to their dev team; asking him if he's heard anything new
from them.



Daniel J. Schneider
Photographer and Journalist
Denver, Colorado
Scrollwright.com
twitter.com/schneidan <http://www.twitter.com/schneidan>
P: 720-732-1763

**Comment by schneidan** [comment]
Tyler replied that the NDN dev team is still working on the best solution
and will update us soon with any new information.



Daniel J. Schneider
Photographer and Journalist
Denver, Colorado
Scrollwright.com
twitter.com/schneidan <http://www.twitter.com/schneidan>
P: 720-732-1763

**Comment by freejoe76** [comment]
Okay that's fine, but we've been waiting months on this. When they actually get something together please create a new issue and reference this one in the issue.
